langchain4j:
  open-ai:
    chat-model:
      base-url: https://open.bigmodel.cn/api/paas/v4
      api-key: bb3ffc1e3b434f81a1346cc361442eb0.ZuqmDz2VKKnf5rpW
      model-name: glm-4-flash
      strict-json-schema: true
      response-format: json_object
      log-requests: true
      log-responses: true
      max-tokens: 8192
    streaming-chat-model:
      base-url: https://open.bigmodel.cn/api/paas/v4
      api-key: bb3ffc1e3b434f81a1346cc361442eb0.ZuqmDz2VKKnf5rpW
      model-name: glm-4-flash
      max-tokens: 8192
      log-requests: true
      log-responses: true